# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/capi1500/Desktop/Platform

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/capi1500/Desktop/Platform

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/capi1500/Desktop/Platform/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/capi1500/Desktop/Platform/CMakeFiles /home/capi1500/Desktop/Platform/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/capi1500/Desktop/Platform/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Platform

# Build rule for target.
Platform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Platform
.PHONY : Platform

# fast build rule for target.
Platform/fast:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/build
.PHONY : Platform/fast

Alphabet/alphabet.o: Alphabet/alphabet.cpp.o

.PHONY : Alphabet/alphabet.o

# target to build an object file
Alphabet/alphabet.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Alphabet/alphabet.cpp.o
.PHONY : Alphabet/alphabet.cpp.o

Alphabet/alphabet.i: Alphabet/alphabet.cpp.i

.PHONY : Alphabet/alphabet.i

# target to preprocess a source file
Alphabet/alphabet.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Alphabet/alphabet.cpp.i
.PHONY : Alphabet/alphabet.cpp.i

Alphabet/alphabet.s: Alphabet/alphabet.cpp.s

.PHONY : Alphabet/alphabet.s

# target to generate assembly for a file
Alphabet/alphabet.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Alphabet/alphabet.cpp.s
.PHONY : Alphabet/alphabet.cpp.s

AnimatedSprite/AnimatedSprite.o: AnimatedSprite/AnimatedSprite.cpp.o

.PHONY : AnimatedSprite/AnimatedSprite.o

# target to build an object file
AnimatedSprite/AnimatedSprite.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/AnimatedSprite/AnimatedSprite.cpp.o
.PHONY : AnimatedSprite/AnimatedSprite.cpp.o

AnimatedSprite/AnimatedSprite.i: AnimatedSprite/AnimatedSprite.cpp.i

.PHONY : AnimatedSprite/AnimatedSprite.i

# target to preprocess a source file
AnimatedSprite/AnimatedSprite.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/AnimatedSprite/AnimatedSprite.cpp.i
.PHONY : AnimatedSprite/AnimatedSprite.cpp.i

AnimatedSprite/AnimatedSprite.s: AnimatedSprite/AnimatedSprite.cpp.s

.PHONY : AnimatedSprite/AnimatedSprite.s

# target to generate assembly for a file
AnimatedSprite/AnimatedSprite.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/AnimatedSprite/AnimatedSprite.cpp.s
.PHONY : AnimatedSprite/AnimatedSprite.cpp.s

AnimatedSprite/Animation.o: AnimatedSprite/Animation.cpp.o

.PHONY : AnimatedSprite/Animation.o

# target to build an object file
AnimatedSprite/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/AnimatedSprite/Animation.cpp.o
.PHONY : AnimatedSprite/Animation.cpp.o

AnimatedSprite/Animation.i: AnimatedSprite/Animation.cpp.i

.PHONY : AnimatedSprite/Animation.i

# target to preprocess a source file
AnimatedSprite/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/AnimatedSprite/Animation.cpp.i
.PHONY : AnimatedSprite/Animation.cpp.i

AnimatedSprite/Animation.s: AnimatedSprite/Animation.cpp.s

.PHONY : AnimatedSprite/Animation.s

# target to generate assembly for a file
AnimatedSprite/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/AnimatedSprite/Animation.cpp.s
.PHONY : AnimatedSprite/Animation.cpp.s

Collectible/collectible.o: Collectible/collectible.cpp.o

.PHONY : Collectible/collectible.o

# target to build an object file
Collectible/collectible.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Collectible/collectible.cpp.o
.PHONY : Collectible/collectible.cpp.o

Collectible/collectible.i: Collectible/collectible.cpp.i

.PHONY : Collectible/collectible.i

# target to preprocess a source file
Collectible/collectible.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Collectible/collectible.cpp.i
.PHONY : Collectible/collectible.cpp.i

Collectible/collectible.s: Collectible/collectible.cpp.s

.PHONY : Collectible/collectible.s

# target to generate assembly for a file
Collectible/collectible.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Collectible/collectible.cpp.s
.PHONY : Collectible/collectible.cpp.s

Counter/counter.o: Counter/counter.cpp.o

.PHONY : Counter/counter.o

# target to build an object file
Counter/counter.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Counter/counter.cpp.o
.PHONY : Counter/counter.cpp.o

Counter/counter.i: Counter/counter.cpp.i

.PHONY : Counter/counter.i

# target to preprocess a source file
Counter/counter.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Counter/counter.cpp.i
.PHONY : Counter/counter.cpp.i

Counter/counter.s: Counter/counter.cpp.s

.PHONY : Counter/counter.s

# target to generate assembly for a file
Counter/counter.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Counter/counter.cpp.s
.PHONY : Counter/counter.cpp.s

Entity/entity.o: Entity/entity.cpp.o

.PHONY : Entity/entity.o

# target to build an object file
Entity/entity.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Entity/entity.cpp.o
.PHONY : Entity/entity.cpp.o

Entity/entity.i: Entity/entity.cpp.i

.PHONY : Entity/entity.i

# target to preprocess a source file
Entity/entity.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Entity/entity.cpp.i
.PHONY : Entity/entity.cpp.i

Entity/entity.s: Entity/entity.cpp.s

.PHONY : Entity/entity.s

# target to generate assembly for a file
Entity/entity.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Entity/entity.cpp.s
.PHONY : Entity/entity.cpp.s

Game/game.o: Game/game.cpp.o

.PHONY : Game/game.o

# target to build an object file
Game/game.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Game/game.cpp.o
.PHONY : Game/game.cpp.o

Game/game.i: Game/game.cpp.i

.PHONY : Game/game.i

# target to preprocess a source file
Game/game.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Game/game.cpp.i
.PHONY : Game/game.cpp.i

Game/game.s: Game/game.cpp.s

.PHONY : Game/game.s

# target to generate assembly for a file
Game/game.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Game/game.cpp.s
.PHONY : Game/game.cpp.s

GraphicString/graphicString.o: GraphicString/graphicString.cpp.o

.PHONY : GraphicString/graphicString.o

# target to build an object file
GraphicString/graphicString.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/GraphicString/graphicString.cpp.o
.PHONY : GraphicString/graphicString.cpp.o

GraphicString/graphicString.i: GraphicString/graphicString.cpp.i

.PHONY : GraphicString/graphicString.i

# target to preprocess a source file
GraphicString/graphicString.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/GraphicString/graphicString.cpp.i
.PHONY : GraphicString/graphicString.cpp.i

GraphicString/graphicString.s: GraphicString/graphicString.cpp.s

.PHONY : GraphicString/graphicString.s

# target to generate assembly for a file
GraphicString/graphicString.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/GraphicString/graphicString.cpp.s
.PHONY : GraphicString/graphicString.cpp.s

GroundObject/groundObject.o: GroundObject/groundObject.cpp.o

.PHONY : GroundObject/groundObject.o

# target to build an object file
GroundObject/groundObject.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/GroundObject/groundObject.cpp.o
.PHONY : GroundObject/groundObject.cpp.o

GroundObject/groundObject.i: GroundObject/groundObject.cpp.i

.PHONY : GroundObject/groundObject.i

# target to preprocess a source file
GroundObject/groundObject.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/GroundObject/groundObject.cpp.i
.PHONY : GroundObject/groundObject.cpp.i

GroundObject/groundObject.s: GroundObject/groundObject.cpp.s

.PHONY : GroundObject/groundObject.s

# target to generate assembly for a file
GroundObject/groundObject.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/GroundObject/groundObject.cpp.s
.PHONY : GroundObject/groundObject.cpp.s

Loader/loader.o: Loader/loader.cpp.o

.PHONY : Loader/loader.o

# target to build an object file
Loader/loader.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Loader/loader.cpp.o
.PHONY : Loader/loader.cpp.o

Loader/loader.i: Loader/loader.cpp.i

.PHONY : Loader/loader.i

# target to preprocess a source file
Loader/loader.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Loader/loader.cpp.i
.PHONY : Loader/loader.cpp.i

Loader/loader.s: Loader/loader.cpp.s

.PHONY : Loader/loader.s

# target to generate assembly for a file
Loader/loader.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Loader/loader.cpp.s
.PHONY : Loader/loader.cpp.s

Object/object.o: Object/object.cpp.o

.PHONY : Object/object.o

# target to build an object file
Object/object.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Object/object.cpp.o
.PHONY : Object/object.cpp.o

Object/object.i: Object/object.cpp.i

.PHONY : Object/object.i

# target to preprocess a source file
Object/object.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Object/object.cpp.i
.PHONY : Object/object.cpp.i

Object/object.s: Object/object.cpp.s

.PHONY : Object/object.s

# target to generate assembly for a file
Object/object.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Object/object.cpp.s
.PHONY : Object/object.cpp.s

PhysicObject/physicObject.o: PhysicObject/physicObject.cpp.o

.PHONY : PhysicObject/physicObject.o

# target to build an object file
PhysicObject/physicObject.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/PhysicObject/physicObject.cpp.o
.PHONY : PhysicObject/physicObject.cpp.o

PhysicObject/physicObject.i: PhysicObject/physicObject.cpp.i

.PHONY : PhysicObject/physicObject.i

# target to preprocess a source file
PhysicObject/physicObject.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/PhysicObject/physicObject.cpp.i
.PHONY : PhysicObject/physicObject.cpp.i

PhysicObject/physicObject.s: PhysicObject/physicObject.cpp.s

.PHONY : PhysicObject/physicObject.s

# target to generate assembly for a file
PhysicObject/physicObject.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/PhysicObject/physicObject.cpp.s
.PHONY : PhysicObject/physicObject.cpp.s

Player/player.o: Player/player.cpp.o

.PHONY : Player/player.o

# target to build an object file
Player/player.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Player/player.cpp.o
.PHONY : Player/player.cpp.o

Player/player.i: Player/player.cpp.i

.PHONY : Player/player.i

# target to preprocess a source file
Player/player.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Player/player.cpp.i
.PHONY : Player/player.cpp.i

Player/player.s: Player/player.cpp.s

.PHONY : Player/player.s

# target to generate assembly for a file
Player/player.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Player/player.cpp.s
.PHONY : Player/player.cpp.s

Sound/sound.o: Sound/sound.cpp.o

.PHONY : Sound/sound.o

# target to build an object file
Sound/sound.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Sound/sound.cpp.o
.PHONY : Sound/sound.cpp.o

Sound/sound.i: Sound/sound.cpp.i

.PHONY : Sound/sound.i

# target to preprocess a source file
Sound/sound.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Sound/sound.cpp.i
.PHONY : Sound/sound.cpp.i

Sound/sound.s: Sound/sound.cpp.s

.PHONY : Sound/sound.s

# target to generate assembly for a file
Sound/sound.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/Sound/sound.cpp.s
.PHONY : Sound/sound.cpp.s

TerrainObject/terrainObject.o: TerrainObject/terrainObject.cpp.o

.PHONY : TerrainObject/terrainObject.o

# target to build an object file
TerrainObject/terrainObject.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/TerrainObject/terrainObject.cpp.o
.PHONY : TerrainObject/terrainObject.cpp.o

TerrainObject/terrainObject.i: TerrainObject/terrainObject.cpp.i

.PHONY : TerrainObject/terrainObject.i

# target to preprocess a source file
TerrainObject/terrainObject.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/TerrainObject/terrainObject.cpp.i
.PHONY : TerrainObject/terrainObject.cpp.i

TerrainObject/terrainObject.s: TerrainObject/terrainObject.cpp.s

.PHONY : TerrainObject/terrainObject.s

# target to generate assembly for a file
TerrainObject/terrainObject.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/TerrainObject/terrainObject.cpp.s
.PHONY : TerrainObject/terrainObject.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Platform.dir/build.make CMakeFiles/Platform.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... package"
	@echo "... package_source"
	@echo "... install/strip"
	@echo "... Platform"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Alphabet/alphabet.o"
	@echo "... Alphabet/alphabet.i"
	@echo "... Alphabet/alphabet.s"
	@echo "... AnimatedSprite/AnimatedSprite.o"
	@echo "... AnimatedSprite/AnimatedSprite.i"
	@echo "... AnimatedSprite/AnimatedSprite.s"
	@echo "... AnimatedSprite/Animation.o"
	@echo "... AnimatedSprite/Animation.i"
	@echo "... AnimatedSprite/Animation.s"
	@echo "... Collectible/collectible.o"
	@echo "... Collectible/collectible.i"
	@echo "... Collectible/collectible.s"
	@echo "... Counter/counter.o"
	@echo "... Counter/counter.i"
	@echo "... Counter/counter.s"
	@echo "... Entity/entity.o"
	@echo "... Entity/entity.i"
	@echo "... Entity/entity.s"
	@echo "... Game/game.o"
	@echo "... Game/game.i"
	@echo "... Game/game.s"
	@echo "... GraphicString/graphicString.o"
	@echo "... GraphicString/graphicString.i"
	@echo "... GraphicString/graphicString.s"
	@echo "... GroundObject/groundObject.o"
	@echo "... GroundObject/groundObject.i"
	@echo "... GroundObject/groundObject.s"
	@echo "... Loader/loader.o"
	@echo "... Loader/loader.i"
	@echo "... Loader/loader.s"
	@echo "... Object/object.o"
	@echo "... Object/object.i"
	@echo "... Object/object.s"
	@echo "... PhysicObject/physicObject.o"
	@echo "... PhysicObject/physicObject.i"
	@echo "... PhysicObject/physicObject.s"
	@echo "... Player/player.o"
	@echo "... Player/player.i"
	@echo "... Player/player.s"
	@echo "... Sound/sound.o"
	@echo "... Sound/sound.i"
	@echo "... Sound/sound.s"
	@echo "... TerrainObject/terrainObject.o"
	@echo "... TerrainObject/terrainObject.i"
	@echo "... TerrainObject/terrainObject.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

